- hosts: all           # применяем ко всем хостав из файла host.ini, файл указываем при вызове плейбука
  gather_facts: no     # не собираем факты (переменные с информацией об хосте) при выполнении плейбука

  tasks:                                        
    - name: Return motd to registered var         # используем команду whoami в командной строке и регистрируем в переменную result
      ansible.builtin.command: whoami
      register: result


    - name: Print return information from the previous task      # выводим на экран переменную result
      ansible.builtin.debug:
        var: result