- hosts: jinoServers

  tasks:
    - name: Remove users
      ansible.builtin.user:
        name: "{{item}}"
        state: absent
        remove: yes
      loop:
        "{{users}}"
      become: yes # <---  выполнить из под рута