- hosts: jinoServers
  gather_facts: no 

  tasks:
    - name: started nginx        # stopped nginx demon
      ansible.builtin.service:
        name: nginx
        state: stopped
      become: yes

    - name: unInstall nginx 
      ansible.builtin.apt:
        name: nginx
        state: absent          # delete   app
        autoremove: yes        # delete  dependencies 
        purge: true            # delete conig files
        update_cache: yes      # update app list in apt          
      become: yes # <---  выполнить из под рута